{% set name = "pymatgen-db" %}
{% set version = "2021.5.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e3a46af726ce2d9087cbbeefcd533364484668d39c65a66e9eae2379e818e27

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - pymatgen >=2022.0.3
    - monty >=0.9.6
    - pymongo >=2.8
    - smoqe

test:
  imports:
    - pymatgen.db
  commands:
    - pip check
  requires: 
    - pip

about:
  home: https://github.com/materialsproject/pymatgen-db
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pymatgen-db provides an addon to the Python Materials Genomics (pymatgen) library that allows the creation of Materials Project-style databases for management of materials data.

  description: |
    Pymatgen-db is a database add-on for the Python Materials Genomics 
    (pymatgen) materials analysis library. It enables the creation of 
    Materials Project-style MongoDB databases for management of materials 
    data. A query engine is also provided to enable the easy translation 
    of MongoDB docs to useful pymatgen objects for analysis purposes.
  doc_url: https://github.com/materialsproject/pymatgen-db
  dev_url: https://github.com/materialsproject/pymatgen-db

extra:
  recipe-maintainers:
    - jan-janssen
    - shyuep
    - mkhorton
