travis:
  secure:
    BINSTAR_TOKEN: Km/6d9+qiGlknZr/Xw3njcd41cTlaDn5cYDit+iCMdySpuo/k3bcY+021uqhuKV87+MRKGzrTpz59NwmvMJ5D8eSzQVsUUqh2QjaSyQTjF04NUAjhcij7zBUM7BLsPC07NgWzt+rPZZD2gh8PPfZPL4xvjrBBj6uVnyn4N+7/ySgIW3S06J6gvdEoE31ui+fu3HPAtBk+0kXz/A7pwzeHM3K6BIUvWEY9boEgdeWBej3M1F+oIzSRZpowt1u2gh+EhD7w3Ze4oZ0ChcRPI6UzvmJ/c68Al2ty2ZBpm7wtfWPSntxNo24oWX6ge7ZoWPnvzN9vWS6REV7ZJG2q1wENxYNTfHW0Oo4+7vMkhZ0qqsd+opzbYadnYlJh1z4ljDHFcrjpkbZ4ZXFayc63BL9fIf+pMdyVA2MXO3dKfX18sCWCWt49D1l+f92fO5fghJGxj+avI/U3Qs5TwS8O+pyMYM/kgJlkEaB3Ld43CHkuMwmpom7jLAu3cq77Ggqp+tTAbvYlTw54I4WDehzOGbj0WvrUIkZ/ner0+gpdhgyeVNHGMzMf57tj430ixROJJUn/0C3gmisGQXnkL0JOzOxJGAzoB19+gZCkoG0HnPL0tW1WI2YyW4C3r20ZDnET4H7DdToKDSA6jjND9xLd8UKQzI6lwLVTMp69GMsD8395rA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: appveyor
bot:
  automerge: true
